name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Robot
      run: |
        export ROBOT=v1.6.0
        export ROBOT_ARGS=-Xmx20G
        export ROBOT_JAR=https://github.com/ontodev/robot/releases/download/$ROBOT/robot.jar
        export ROBOT_JAR=${ROBOT_JAR}
        wget $ROBOT_JAR -O $HOME/robot.jar
        wget https://raw.githubusercontent.com/ontodev/robot/$ROBOT/bin/robot -O $HOME/robot
        chmod +x $HOME/robot && chmod +x $HOME/robot.jar
    - name: Import neuprint connectome
      run: |
        cd $GITHUB_WORKSPACE/src/VFB_connectomics_import
        python src/VFB_connectomics_import/CATMAID_script_runner.py -t 0 -d catmaid_fafb -c_e https://fafb.catmaid.virtualflybrain.org/
    - name: Robot
      run: |
        echo RUN ROBOT JOB HERE      
    
